import './globals.css'
import { Montserrat} from 'next/font/google'


const montserrat = Montserrat({
    subsets: ['latin'], 
    weight: ['100', '400', '700' ] 
  })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  keywords: 'junior proyects, web design, javascript, nextjs'
}

export default function RootLayout({children,}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        
        <main className='container'>
            
        </main>
        
      </body>
    </html>
  )
}
