'use client'
import './globals.css'
import {GlobalProvider} from './context/GlobalContext'
import Navigation from '@/components/Navigation'
//import { Montserrat} from 'next/font/google'


// const montserrat = Montserrat({
//     subsets: ['latin'], 
//     weight: ['100', '400', '700' ] 
//   })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  keywords: 'junior proyects, web design, javascript, nextjs'
}

export default function RootLayout({children,}: {
  children: React.ReactNode
}) {
  return (
    <GlobalProvider>
      <html lang="en">
        <body >
          
          <main className='container'>
            <Navigation/>
              {children}
          </main>
          
        </body>
      </html>
    </GlobalProvider>
  )
}
