'use client'
import LoginForm from '../../components/LoginForm'

export const metadata = {
  title: 'Login',
  description: 'Generated by create next app',
  keywords: 'junior proyects, web design, javascript, nextjs'
}

export default function RootLayout({children,}: {
  children: React.ReactNode
}) {

  return (
        <main className='container flex-center'>
            <div className="loginContainer">
                <LoginForm />    
            </div>
            <div className="contentContainer">
                <h1>l</h1>
            </div>
            
        </main>
  
  )
}
